// Auto-generated Vite asset map for Mechanical Maze Tile Kit V1.
const modules = import.meta.glob('../runtime/**/*.png', { eager: true, query: '?url', import: 'default' });
const asset = p => modules[`../runtime/${p}`] || '';

export const MAZE_ASSETS = {
  tiles: {
    baseGrid: asset('tiles/base_grid.png'),
    baseSteelDark: asset('tiles/base_steel_dark.png'),
    baseSteelLight: asset('tiles/base_steel_light.png'),
    baseWood: asset('tiles/base_wood.png'),
    blockCrate: asset('tiles/block_crate.png'),
    blockRock: asset('tiles/block_rock.png'),
    bridgeClosed: asset('tiles/bridge_closed.png'),
    bridgeOpen: asset('tiles/bridge_open.png'),
    bridgeRotating: asset('tiles/bridge_rotating.png'),
    crusherActive: asset('tiles/crusher_active.png'),
    crusherIdle: asset('tiles/crusher_idle.png'),
    deadEndE: asset('tiles/dead_end_e.png'),
    deadEndN: asset('tiles/dead_end_n.png'),
    deadEndS: asset('tiles/dead_end_s.png'),
    deadEndW: asset('tiles/dead_end_w.png'),
    elevatorBottom: asset('tiles/elevator_bottom.png'),
    elevatorMoving: asset('tiles/elevator_moving.png'),
    elevatorTop: asset('tiles/elevator_top.png'),
    fanIdle: asset('tiles/fan_idle.png'),
    fanSpinning: asset('tiles/fan_spinning.png'),
    gateClosed: asset('tiles/gate_closed.png'),
    gateOpen: asset('tiles/gate_open.png'),
    gateOpening: asset('tiles/gate_opening.png'),
    magnetActive: asset('tiles/magnet_active.png'),
    magnetOff: asset('tiles/magnet_off.png'),
    oneWayRail: asset('tiles/one_way_rail.png'),
    pitFail: asset('tiles/pit_fail.png'),
    pitIdle: asset('tiles/pit_idle.png'),
    portalBlue: asset('tiles/portal_blue.png'),
    portalPurple: asset('tiles/portal_purple.png'),
    pressurePadPressed: asset('tiles/pressure_pad_pressed.png'),
    pressurePadUp: asset('tiles/pressure_pad_up.png'),
    railCornerNe: asset('tiles/rail_corner_ne.png'),
    railCornerNw: asset('tiles/rail_corner_nw.png'),
    railCornerSe: asset('tiles/rail_corner_se.png'),
    railCornerSw: asset('tiles/rail_corner_sw.png'),
    railCross: asset('tiles/rail_cross.png'),
    railStraightH: asset('tiles/rail_straight_h.png'),
    railStraightV: asset('tiles/rail_straight_v.png'),
    railTeeEsw: asset('tiles/rail_tee_esw.png'),
    railTeeNes: asset('tiles/rail_tee_nes.png'),
    railTeeNsw: asset('tiles/rail_tee_nsw.png'),
    rotatableHover: asset('tiles/rotatable_hover.png'),
    rotatableIdle: asset('tiles/rotatable_idle.png'),
    rotatableRotating: asset('tiles/rotatable_rotating.png'),
    rotatableSnapped: asset('tiles/rotatable_snapped.png'),
    splitterActive: asset('tiles/splitter_active.png'),
    splitterIdle: asset('tiles/splitter_idle.png'),
    springCompressed: asset('tiles/spring_compressed.png'),
    springIdle: asset('tiles/spring_idle.png'),
    springRelease: asset('tiles/spring_release.png'),
    startSocketActive: asset('tiles/start_socket_active.png'),
    startSocketIdle: asset('tiles/start_socket_idle.png'),
  },
  objects: {
    ballBlue: asset('objects/ball_blue.png'),
    ballSteelA: asset('objects/ball_steel_a.png'),
    ballSteelB: asset('objects/ball_steel_b.png'),
    goalActive: asset('objects/goal_active.png'),
    goalIdle: asset('objects/goal_idle.png'),
    goalSuccess: asset('objects/goal_success.png'),
    starCollect: asset('objects/star_collect.png'),
    starIdle: asset('objects/star_idle.png'),
    starSuccess: asset('objects/star_success.png'),
  },
  fx: {
    ballTrail: asset('fx/ball_trail.png'),
    failSplash: asset('fx/fail_splash.png'),
    fanWind: asset('fx/fan_wind.png'),
    gateSparks: asset('fx/gate_sparks.png'),
    goalGlow: asset('fx/goal_glow.png'),
    magnetField: asset('fx/magnet_field.png'),
    rollTrail: asset('fx/roll_trail.png'),
    springDust: asset('fx/spring_dust.png'),
    starBurst: asset('fx/star_burst.png'),
  },
  ui: {
    failX: asset('ui/fail_x.png'),
    hintPath: asset('ui/hint_path.png'),
    iconHint: asset('ui/icon_hint.png'),
    iconPause: asset('ui/icon_pause.png'),
    iconPlay: asset('ui/icon_play.png'),
    iconRestart: asset('ui/icon_restart.png'),
    iconSettings: asset('ui/icon_settings.png'),
    moveIndicator: asset('ui/move_indicator.png'),
    starEmpty: asset('ui/star_empty.png'),
    starLarge: asset('ui/star_large.png'),
    starSmall: asset('ui/star_small.png'),
    successCheck: asset('ui/success_check.png'),
  },
};

export default MAZE_ASSETS;
