// Auto-generated code-ready asset map for One Move Puzzle
// Paths are relative to the app public/root directory.

export const WORKSHOP_ASSETS = {
  base: {
    boardWorkshopBase: '/assets/workshop/base/board_workshop_base.png',
    boardSidePanel: '/assets/workshop/base/board_side_panel.png',
    boardCornerCap: '/assets/workshop/base/board_corner_cap.png',
  },
  tracks: {
    trackStraight: '/assets/workshop/tracks/track_straight.png',
    trackCurveLeft: '/assets/workshop/tracks/track_curve_left.png',
    trackCurveRight: '/assets/workshop/tracks/track_curve_right.png',
    trackSCurve: '/assets/workshop/tracks/track_s_curve.png',
    trackEnd: '/assets/workshop/tracks/track_end.png',
    trackT: '/assets/workshop/tracks/track_t.png',
    trackHalfStraight: '/assets/workshop/tracks/track_half_straight.png',
    trackJoiner: '/assets/workshop/tracks/track_joiner.png',
    trackForkLeft: '/assets/workshop/tracks/track_fork_left.png',
    trackForkRight: '/assets/workshop/tracks/track_fork_right.png',
    trackCross: '/assets/workshop/tracks/track_cross.png',
    trackBridge: '/assets/workshop/tracks/track_bridge.png',
    trackRiserShort: '/assets/workshop/tracks/track_riser_short.png',
    trackRiserTall: '/assets/workshop/tracks/track_riser_tall.png',
    trackDropGate: '/assets/workshop/tracks/track_drop_gate.png',
    trackSpinnerSwitch: '/assets/workshop/tracks/track_spinner_switch.png',
    trackFlipFlap: '/assets/workshop/tracks/track_flip_flap.png',
    trackFunnel: '/assets/workshop/tracks/track_funnel.png',
    trackCurveTightLeft: '/assets/workshop/tracks/track_curve_tight_left.png',
    trackCurveTightRight: '/assets/workshop/tracks/track_curve_tight_right.png',
    trackCurveWideLeft: '/assets/workshop/tracks/track_curve_wide_left.png',
    trackCurveWideRight: '/assets/workshop/tracks/track_curve_wide_right.png',
  },
  pins: {
    ballHolder: '/assets/workshop/pins/ball_holder.png',
    pinBlue: '/assets/workshop/pins/pin_blue.png',
    pinRed: '/assets/workshop/pins/pin_red.png',
    pinSocket: '/assets/workshop/pins/pin_socket.png',
    pinEnd: '/assets/workshop/pins/pin_end.png',
  },
  hardware: {
    bracketCorner: '/assets/workshop/hardware/bracket_corner.png',
    bracketStraight: '/assets/workshop/hardware/bracket_straight.png',
    bracketU: '/assets/workshop/hardware/bracket_u.png',
    screw: '/assets/workshop/hardware/screw.png',
    screwCap: '/assets/workshop/hardware/screw_cap.png',
    metalPlate: '/assets/workshop/hardware/metal_plate.png',
    postWood: '/assets/workshop/hardware/post_wood.png',
    postMetal: '/assets/workshop/hardware/post_metal.png',
    chainShort: '/assets/workshop/hardware/chain_short.png',
    chainLong: '/assets/workshop/hardware/chain_long.png',
  },
  mechanisms: {
    buttonYellow: '/assets/workshop/mechanisms/button_yellow.png',
    buttonGreen: '/assets/workshop/mechanisms/button_green.png',
    leverRed: '/assets/workshop/mechanisms/lever_red.png',
    leverBlue: '/assets/workshop/mechanisms/lever_blue.png',
    springBumper: '/assets/workshop/mechanisms/spring_bumper.png',
    gear: '/assets/workshop/mechanisms/gear.png',
    wheelValve: '/assets/workshop/mechanisms/wheel_valve.png',
    bell: '/assets/workshop/mechanisms/bell.png',
    fan: '/assets/workshop/mechanisms/fan.png',
    conveyor: '/assets/workshop/mechanisms/conveyor.png',
    magnet: '/assets/workshop/mechanisms/magnet.png',
    portal: '/assets/workshop/mechanisms/portal.png',
    gateSlider: '/assets/workshop/mechanisms/gate_slider.png',
    gateLockedRound: '/assets/workshop/mechanisms/gate_locked_round.png',
    pistonPusher: '/assets/workshop/mechanisms/piston_pusher.png',
    hammerStriker: '/assets/workshop/mechanisms/hammer_striker.png',
    springPadSmall: '/assets/workshop/mechanisms/spring_pad_small.png',
    bumperRound: '/assets/workshop/mechanisms/bumper_round.png',
    bumperTriangle: '/assets/workshop/mechanisms/bumper_triangle.png',
    lampIndicatorGreen: '/assets/workshop/mechanisms/lamp_indicator_green.png',
    lampIndicatorRed: '/assets/workshop/mechanisms/lamp_indicator_red.png',
    checkpointRing: '/assets/workshop/mechanisms/checkpoint_ring.png',
    crankHandle: '/assets/workshop/mechanisms/crank_handle.png',
    pulleySingle: '/assets/workshop/mechanisms/pulley_single.png',
    pulleyDouble: '/assets/workshop/mechanisms/pulley_double.png',
    ropeHook: '/assets/workshop/mechanisms/rope_hook.png',
  },
  goals: {
    goalSocket: '/assets/workshop/goals/goal_socket.png',
    goalYellow: '/assets/workshop/goals/goal_yellow.png',
    star: '/assets/workshop/goals/star.png',
    ballBlue: '/assets/workshop/goals/ball_blue.png',
    ballSteel: '/assets/workshop/goals/ball_steel.png',
    starSocket: '/assets/workshop/goals/star_socket.png',
    coinBrass: '/assets/workshop/goals/coin_brass.png',
  },
  decor: {
    crateWood: '/assets/workshop/decor/crate_wood.png',
    stopperWood: '/assets/workshop/decor/stopper_wood.png',
    signArrow: '/assets/workshop/decor/sign_arrow.png',
    flagBlue: '/assets/workshop/decor/flag_blue.png',
    signStart: '/assets/workshop/decor/sign_start.png',
    signGoal: '/assets/workshop/decor/sign_goal.png',
  },
};

export default WORKSHOP_ASSETS;
